### ISSUE TITLE
fork for intellij?

### ISSUE THREAD

**Issue by pinkdevelops** [Brackets-Themes/80sBaby#2]
I use this in Brackets, its the best scheme i've ever found.  Is there anything similar or a potential fork for IntelliJ for Java?

**Comment by MiguelCastillo** [comment]
@pinkdevelops I have no idea. This is a custom theme that @larz0 created.  Really doubt that it exists in other editors...  Feel free to port it to other editors.  Perhaps @larz0 can give you his thoughts on this.

**Comment by larz0** [comment]
@pinkdevelops this is open source so feel free to reuse this elsewhere :+1: Thanks for ping @MiguelCastillo :)

**Comment by pinkdevelops** [comment]
@MiguelCastillo @larz0 Thanks, I appreciate it great theme i may try to port over and will post here if so.
